In [1]:
import requests

url = "https://yelp-reviews.p.rapidapi.com/business-search"

querystring = {"query":"rooftop bars","location":"Berlin","start":"0","yelp_domain":"yelp.com"}

headers = {
	"X-RapidAPI-Key": "",
	"X-RapidAPI-Host": "yelp-reviews.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'status': 'OK', 'request_id': '2956d0f3-b721-4b2a-b26d-793f32acda5f', 'data': [{'id': '8Eg2DjqabhRpMPt5Sjj04g', 'alias': 'klunkerkranich-berlin', 'name': 'Klunkerkranich', 'address': 'Karl-Marx-Str. 66, 12043 Berlin, Germany', 'latitude': 52.4821600866795, 'longitude': 13.431854, 'business_page_link': 'https://www.yelp.com/biz/klunkerkranich-berlin', 'rating': 4.3, 'review_count': 122, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/qywQtYIEtSzBh2N_xtpcBg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/8Eg2DjqabhRpMPt5Sjj04g', 'phone': '+4915124504255', 'country': 'DE', 'neighborhoods': ['Neukölln']}, {'id': 'Ojzt5DTrlDk22tz50ludug', 'alias': 'gallery-rooftop-bar-berlin', 'name': 'Gallery Rooftop Bar', 'address': 'Mühlenstr. 19, 10243 Berlin, Germany', 'latitude': 52.504494, 'longitude': 13.442135, 'business_page_link': 'https://www.yelp.com/biz/gallery-rooftop-bar-berlin', 'rating': 5, 'review_count': 2, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Np84oCJv9Y2N61tWtYQXHg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/Ojzt5DTrlDk22tz50ludug', 'phone': '+49302977206908', 'country': 'DE', 'neighborhoods': ['Friedrichshain']}, {'id': '9BmXtcLrCnOPzQHxMV7i8g', 'alias': 'rooftop-terrace-bar-und-lounge-berlin', 'name': 'Rooftop Terrace Bar & Lounge', 'address': 'Behrenstr. 37, 10117 Berlin, Germany', 'latitude': 52.5157663, 'longitude': 13.394096, 'business_page_link': 'https://www.yelp.com/biz/rooftop-terrace-bar-und-lounge-berlin', 'rating': 3.4, 'review_count': 5, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/q4O7a7bPTmBIP-csz_i35w/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/9BmXtcLrCnOPzQHxMV7i8g', 'phone': '+49304606091260', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': '6ZQWI3ni4OQ_ZAmQ2_9E0Q', 'alias': 'monkey-bar-berlin', 'name': 'Monkey Bar', 'address': 'Budapester Str. 40, 10787 Berlin, Germany', 'latitude': 52.5053774, 'longitude': 13.3368904, 'business_page_link': 'https://www.yelp.com/biz/monkey-bar-berlin', 'rating': 3.3, 'review_count': 164, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Ng4Bei7Q6lCWdAM6m8RJ7Q/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/6ZQWI3ni4OQ_ZAmQ2_9E0Q', 'phone': '+4930120221210', 'country': 'DE', 'neighborhoods': ['Wilmersdorf']}, {'id': '-9VGTyGBqFNrmpAUYyVhKA', 'alias': 'bebel-bar-und-lounge-berlin', 'name': 'Bebel Bar & Lounge', 'address': 'Behrenstr. 37, 10117 Berlin, Germany', 'latitude': 52.51579, 'longitude': 13.394244, 'business_page_link': 'https://www.yelp.com/biz/bebel-bar-und-lounge-berlin', 'rating': 4, 'review_count': 17, 'price_range': '€€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/0NtlTjOwm2UGiDxuwAxDIg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/-9VGTyGBqFNrmpAUYyVhKA', 'phone': '+49304606090', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': '4R6nWG1_i5900ceCeTgrow', 'alias': 'soho-house-berlin', 'name': 'Soho House', 'address': 'Torstr. 1, 10119 Berlin, Germany', 'latitude': 52.5276093346336, 'longitude': 13.41547273, 'business_page_link': 'https://www.yelp.com/biz/soho-house-berlin', 'rating': 3.8, 'review_count': 88, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/RykxBgrtf35vx4KKlLxeOA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/4R6nWG1_i5900ceCeTgrow', 'phone': '+49304050440', 'country': 'DE', 'neighborhoods': ['Prenzlauer Berg']}, {'id': '_b6tDe10xS2Z7fOVKNOEDQ', 'alias': 'deck-5-berlin', 'name': 'Deck 5', 'address': 'Schönhauser Allee 79, 10439 Berlin, Germany', 'latitude': 52.5495606, 'longitude': 13.4151297, 'business_page_link': 'https://www.yelp.com/biz/deck-5-berlin', 'rating': 3.6, 'review_count': 109, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/ls0OE488tz6sP4xGD3_cBQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/_b6tDe10xS2Z7fOVKNOEDQ', 'phone': '+493041728905', 'country': 'DE', 'neighborhoods': ['Prenzlauer Berg']}, {'id': 'mzT41QvataJZNGgiV2jqiA', 'alias': 'weekend-club-berlin', 'name': 'Weekend Club', 'address': 'Alexanderstr. 7, 10178 Berlin, Germany', 'latitude': 52.5230803169503, 'longitude': 13.4164894571778, 'business_page_link': 'https://www.yelp.com/biz/weekend-club-berlin', 'rating': 3.1, 'review_count': 114, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Nrplz89Jah0xKvH-YeePpQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/mzT41QvataJZNGgiV2jqiA', 'phone': '+493025899366', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': 'vnX9Iotdz5EEdmii6HKP9w', 'alias': 'the-circus-berlin-4', 'name': 'The Circus', 'address': 'Rosenthaler Str. 1, 10119 Berlin, Germany', 'latitude': 52.5294031, 'longitude': 13.4013102, 'business_page_link': 'https://www.yelp.com/biz/the-circus-berlin-4', 'rating': 4.5, 'review_count': 35, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/2XeBvpVOo_jPDHDnMP3_RA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/vnX9Iotdz5EEdmii6HKP9w', 'phone': '+493020003939', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': 'BVd9FjFR_ho9eTtgTm_GjQ', 'alias': 'amano-rooftop-bar-berlin-3', 'name': 'Amano Rooftop Bar', 'address': 'Auguststr. 43, 10119 Berlin, Germany', 'latitude': 52.5282457, 'longitude': 13.4028227, 'business_page_link': 'https://www.yelp.com/biz/amano-rooftop-bar-berlin-3', 'rating': 3.8, 'review_count': 21, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/TGVNCXfzPNy1oyFYbUOgwQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/BVd9FjFR_ho9eTtgTm_GjQ', 'phone': '+4949308094150', 'country': 'DE', 'neighborhoods': ['Mitte']}]}

In [2]:
print(response.json()['data'])

[{'id': '8Eg2DjqabhRpMPt5Sjj04g', 'alias': 'klunkerkranich-berlin', 'name': 'Klunkerkranich', 'address': 'Karl-Marx-Str. 66, 12043 Berlin, Germany', 'latitude': 52.4821600866795, 'longitude': 13.431854, 'business_page_link': 'https://www.yelp.com/biz/klunkerkranich-berlin', 'rating': 4.3, 'review_count': 122, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/qywQtYIEtSzBh2N_xtpcBg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/8Eg2DjqabhRpMPt5Sjj04g', 'phone': '+4915124504255', 'country': 'DE', 'neighborhoods': ['Neukölln']}, {'id': 'Ojzt5DTrlDk22tz50ludug', 'alias': 'gallery-rooftop-bar-berlin', 'name': 'Gallery Rooftop Bar', 'address': 'Mühlenstr. 19, 10243 Berlin, Germany', 'latitude': 52.504494, 'longitude': 13.442135, 'business_page_link': 'https://www.yelp.com/biz/gallery-rooftop-bar-berlin', 'rating': 5, 'review_count': 2, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Np84oCJv9Y2N61tWtYQXHg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/Ojzt5DTrlDk22tz50ludug', 'phone': '+49302977206908', 'country': 'DE', 'neighborhoods': ['Friedrichshain']}, {'id': '9BmXtcLrCnOPzQHxMV7i8g', 'alias': 'rooftop-terrace-bar-und-lounge-berlin', 'name': 'Rooftop Terrace Bar & Lounge', 'address': 'Behrenstr. 37, 10117 Berlin, Germany', 'latitude': 52.5157663, 'longitude': 13.394096, 'business_page_link': 'https://www.yelp.com/biz/rooftop-terrace-bar-und-lounge-berlin', 'rating': 3.4, 'review_count': 5, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/q4O7a7bPTmBIP-csz_i35w/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/9BmXtcLrCnOPzQHxMV7i8g', 'phone': '+49304606091260', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': '6ZQWI3ni4OQ_ZAmQ2_9E0Q', 'alias': 'monkey-bar-berlin', 'name': 'Monkey Bar', 'address': 'Budapester Str. 40, 10787 Berlin, Germany', 'latitude': 52.5053774, 'longitude': 13.3368904, 'business_page_link': 'https://www.yelp.com/biz/monkey-bar-berlin', 'rating': 3.3, 'review_count': 164, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Ng4Bei7Q6lCWdAM6m8RJ7Q/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/6ZQWI3ni4OQ_ZAmQ2_9E0Q', 'phone': '+4930120221210', 'country': 'DE', 'neighborhoods': ['Wilmersdorf']}, {'id': '-9VGTyGBqFNrmpAUYyVhKA', 'alias': 'bebel-bar-und-lounge-berlin', 'name': 'Bebel Bar & Lounge', 'address': 'Behrenstr. 37, 10117 Berlin, Germany', 'latitude': 52.51579, 'longitude': 13.394244, 'business_page_link': 'https://www.yelp.com/biz/bebel-bar-und-lounge-berlin', 'rating': 4, 'review_count': 17, 'price_range': '€€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/0NtlTjOwm2UGiDxuwAxDIg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/-9VGTyGBqFNrmpAUYyVhKA', 'phone': '+49304606090', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': '4R6nWG1_i5900ceCeTgrow', 'alias': 'soho-house-berlin', 'name': 'Soho House', 'address': 'Torstr. 1, 10119 Berlin, Germany', 'latitude': 52.5276093346336, 'longitude': 13.41547273, 'business_page_link': 'https://www.yelp.com/biz/soho-house-berlin', 'rating': 3.8, 'review_count': 88, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/RykxBgrtf35vx4KKlLxeOA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/4R6nWG1_i5900ceCeTgrow', 'phone': '+49304050440', 'country': 'DE', 'neighborhoods': ['Prenzlauer Berg']}, {'id': '_b6tDe10xS2Z7fOVKNOEDQ', 'alias': 'deck-5-berlin', 'name': 'Deck 5', 'address': 'Schönhauser Allee 79, 10439 Berlin, Germany', 'latitude': 52.5495606, 'longitude': 13.4151297, 'business_page_link': 'https://www.yelp.com/biz/deck-5-berlin', 'rating': 3.6, 'review_count': 109, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/ls0OE488tz6sP4xGD3_cBQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/_b6tDe10xS2Z7fOVKNOEDQ', 'phone': '+493041728905', 'country': 'DE', 'neighborhoods': ['Prenzlauer Berg']}, {'id': 'mzT41QvataJZNGgiV2jqiA', 'alias': 'weekend-club-berlin', 'name': 'Weekend Club', 'address': 'Alexanderstr. 7, 10178 Berlin, Germany', 'latitude': 52.5230803169503, 'longitude': 13.4164894571778, 'business_page_link': 'https://www.yelp.com/biz/weekend-club-berlin', 'rating': 3.1, 'review_count': 114, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Nrplz89Jah0xKvH-YeePpQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/mzT41QvataJZNGgiV2jqiA', 'phone': '+493025899366', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': 'vnX9Iotdz5EEdmii6HKP9w', 'alias': 'the-circus-berlin-4', 'name': 'The Circus', 'address': 'Rosenthaler Str. 1, 10119 Berlin, Germany', 'latitude': 52.5294031, 'longitude': 13.4013102, 'business_page_link': 'https://www.yelp.com/biz/the-circus-berlin-4', 'rating': 4.5, 'review_count': 35, 'price_range': '€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/2XeBvpVOo_jPDHDnMP3_RA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/vnX9Iotdz5EEdmii6HKP9w', 'phone': '+493020003939', 'country': 'DE', 'neighborhoods': ['Mitte']}, {'id': 'BVd9FjFR_ho9eTtgTm_GjQ', 'alias': 'amano-rooftop-bar-berlin-3', 'name': 'Amano Rooftop Bar', 'address': 'Auguststr. 43, 10119 Berlin, Germany', 'latitude': 52.5282457, 'longitude': 13.4028227, 'business_page_link': 'https://www.yelp.com/biz/amano-rooftop-bar-berlin-3', 'rating': 3.8, 'review_count': 21, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/TGVNCXfzPNy1oyFYbUOgwQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/BVd9FjFR_ho9eTtgTm_GjQ', 'phone': '+4949308094150', 'country': 'DE', 'neighborhoods': ['Mitte']}]

In [36]:
import pandas as pd
list=[]
data=[]
for i in range(len(response.json()['data'])):
    list=[response.json()['data'][i]['name'],response.json()['data'][i]['latitude'],response.json()['data'][i]['longitude'],response.json()['data'][i]['rating'],response.json()['data'][i]['review_count'],response.json()['data'][i]['price_range']]
    data.append(list)
df=pd.DataFrame(data)
df.columns=['name','latitude','longtitude','rating','review count','price range']
df['city']="Berlin"
df

,name,latitude,longtitude,rating,review count,price range,city
0,Klunkerkranich,52.482160,13.431854,4.3,122,€€,Berlin
1,Gallery Rooftop Bar,52.504494,13.442135,5.0,2,,Berlin
2,Rooftop Terrace Bar & Lounge,52.515766,13.394096,3.4,5,,Berlin
3,Monkey Bar,52.505377,13.336890,3.3,164,€€€,Berlin
4,Bebel Bar & Lounge,52.515790,13.394244,4.0,17,€€€€,Berlin
5,Soho House,52.527609,13.415473,3.8,88,€€€,Berlin
6,Deck 5,52.549561,13.415130,3.6,109,€€,Berlin
7,Weekend Club,52.523080,13.416489,3.1,114,€€€,Berlin
8,The Circus,52.529403,13.401310,4.5,35,€€,Berlin
9,Amano Rooftop Bar,52.528246,13.402823,3.8,21,€€€,Berlin

In [32]:
import requests

url = "https://yelp-reviews.p.rapidapi.com/business-search"

querystring = {"query":"rooftop bars","location":"Manheim","start":"0","yelp_domain":"yelp.com"}

headers = {
	"X-RapidAPI-Key": "",
	"X-RapidAPI-Host": "yelp-reviews.p.rapidapi.com"
}

response1 = requests.get(url, headers=headers, params=querystring)

print(response1.json())

{'status': 'OK', 'request_id': 'da44044a-a16a-4979-a906-bc33effe12f7', 'data': [{'id': 'hGxIe-LFajVY7ntucLv8jQ', 'alias': 'the-exchange-lancaster-2', 'name': 'The Exchange', 'address': '25 S Queen St, Lancaster, PA 17603', 'latitude': 40.037094321297786, 'longitude': -76.30514708456286, 'business_page_link': 'https://www.yelp.com/biz/the-exchange-lancaster-2', 'rating': 3.6, 'review_count': 143, 'price_range': '$$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/N3urHi0h54Pz4HVcga8MOQ/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/hGxIe-LFajVY7ntucLv8jQ', 'phone': '+17172074096', 'country': 'US'}, {'id': '7-bT5o1QeRPbZW_UVgLGsA', 'alias': 'the-sandwich-factory-sports-lounge-neffsville', 'name': 'The Sandwich Factory Sports Lounge', 'address': '2520 Lititz Pike, Neffsville, PA 17601', 'latitude': 40.0952719, 'longitude': -76.3054233, 'business_page_link': 'https://www.yelp.com/biz/the-sandwich-factory-sports-lounge-neffsville', 'rating': 3.2, 'review_count': 83, 'price_range': '$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/wdiV3Q21qgnC6weR41po6A/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/7-bT5o1QeRPbZW_UVgLGsA', 'phone': '+17175818180', 'country': 'US'}, {'id': 'JRDlc2ncVcUHQcXT6qz3Uw', 'alias': 'altana-rooftop-lounge-lancaster', 'name': 'Altana Rooftop lounge', 'address': '26 E King St, Lancaster, PA 17602', 'latitude': 40.0376823, 'longitude': -76.3043172, 'business_page_link': 'https://www.yelp.com/biz/altana-rooftop-lounge-lancaster', 'rating': 2.4, 'review_count': 88, 'price_range': '$$$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/SF6iRE0fOx0rgTnftDVSZA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/JRDlc2ncVcUHQcXT6qz3Uw', 'phone': '+17176902347', 'country': 'US'}, {'id': 'FZM-c6bNimdwy0FIn6hBQg', 'alias': 'lancaster-marriott-at-penn-square-lancaster', 'name': 'Lancaster Marriott at Penn Square', 'address': '25 S Queen St, Lancaster, PA 17603', 'latitude': 40.0369099, 'longitude': -76.30492799999999, 'business_page_link': 'https://www.yelp.com/biz/lancaster-marriott-at-penn-square-lancaster', 'rating': 3.2, 'review_count': 142, 'price_range': '$$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/Au3sIlA6rdP7auEgkttcrA/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/FZM-c6bNimdwy0FIn6hBQg', 'phone': '+17172391600', 'country': 'US'}, {'id': 'MMBGBiXcNMImDzttne4YYQ', 'alias': '551-west-lancaster', 'name': '551 West', 'address': '551 W King St, Lancaster, PA 17603', 'latitude': 40.0371513366699, 'longitude': -76.3166046142578, 'business_page_link': 'https://www.yelp.com/biz/551-west-lancaster', 'rating': 3.7, 'review_count': 103, 'price_range': '$$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/sGhRm9eqt_2K7PRvPcqb3g/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/MMBGBiXcNMImDzttne4YYQ', 'phone': '+17172083658', 'country': 'US'}, {'id': 'Qcd7DWMq2FxaGMjj_PEasg', 'alias': 'tellus360-lancaster', 'name': 'Tellus360', 'address': '24 E King St, Lancaster, PA 17602', 'latitude': 40.037694, 'longitude': -76.30443, 'business_page_link': 'https://www.yelp.com/biz/tellus360-lancaster', 'rating': 3.7, 'review_count': 167, 'price_range': '$$', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/o3kCFL23HVVFaI6JSnOZHw/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/Qcd7DWMq2FxaGMjj_PEasg', 'phone': '+17173931660', 'country': 'US'}, {'id': 'LR0itn6-q5t1Ck8RmtwJUA', 'alias': 'plough-lancaster', 'name': 'Plough', 'address': '25 S Queen St, Lancaster, PA 17603', 'latitude': 40.0369099, 'longitude': -76.30492799999999, 'business_page_link': 'https://www.yelp.com/biz/plough-lancaster', 'rating': 3.6, 'review_count': 89, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/7Lky5xZChoNcyjMTZdaazg/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/LR0itn6-q5t1Ck8RmtwJUA', 'phone': '+17172074095', 'country': 'US'}]}

In [37]:
list1=[]
data1=[]
for i in range(len(response1.json()['data'])):
    list1=[response1.json()['data'][i]['name'],response1.json()['data'][i]['latitude'],response1.json()['data'][i]['longitude'],response1.json()['data'][i]['rating'],response1.json()['data'][i]['review_count'],response1.json()['data'][i]['price_range']]
    data1.append(list1)
df1=pd.DataFrame(data1)
df1.columns=['name','latitude','longtitude','rating','review count','price range']
df1['city']="Manheim"
df1

,name,latitude,longtitude,rating,review count,price range,city
0,The Exchange,40.037094,-76.305147,3.6,143,$$,Manheim
1,The Sandwich Factory Sports Lounge,40.095272,-76.305423,3.2,83,$,Manheim
2,Altana Rooftop lounge,40.037682,-76.304317,2.4,88,$$$,Manheim
3,Lancaster Marriott at Penn Square,40.036910,-76.304928,3.2,142,$$,Manheim
4,551 West,40.037151,-76.316605,3.7,103,$$,Manheim
5,Tellus360,40.037694,-76.304430,3.7,167,$$,Manheim
6,Plough,40.036910,-76.304928,3.6,89,,Manheim

In [47]:
import requests

url = "https://yelp-reviews.p.rapidapi.com/business-search"

querystring = {"query":"rooftop bars","location":"Frankfurt","start":"0","yelp_domain":"yelp.com"}

headers = {
	"X-RapidAPI-Key": "",
	"X-RapidAPI-Host": "yelp-reviews.p.rapidapi.com"
}

response2 = requests.get(url, headers=headers, params=querystring)

print(response2.json())

{'status': 'OK', 'request_id': 'aa9bca5a-f5fb-40b8-9ee7-b5393939b4c5', 'data': [{'id': 'zG4-NeUvloIr_43SOwT4ag', 'alias': 'luginsland-frankfurt-am-main', 'name': 'LugInsLand', 'address': 'Eschenheimer Tor 2, 60318 Frankfurt am Main, Germany', 'latitude': 50.1175261, 'longitude': 8.679976, 'business_page_link': 'https://www.yelp.com/biz/luginsland-frankfurt-am-main', 'rating': 3.4, 'review_count': 96, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/SABs2srdSUtkr6DDI4nCXw/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/zG4-NeUvloIr_43SOwT4ag', 'phone': '+4969989728500', 'country': 'DE', 'neighborhoods': ['Innenstadt']}, {'id': 'bIrI4sPYzBclvQOkRpwYgQ', 'alias': 'gekko-house-frankfurt-am-main', 'name': 'Gekko House', 'address': 'Mainzer Landstr. 167, 60327 Frankfurt am Main, Germany', 'latitude': 50.1060857, 'longitude': 8.652832799999999, 'business_page_link': 'https://www.yelp.com/biz/gekko-house-frankfurt-am-main', 'rating': 2.5, 'review_count': 2, 'price_range': '', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/gD78uP8UNfRi5gAxx1M7Xw/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/bIrI4sPYzBclvQOkRpwYgQ', 'phone': '+49692991430', 'country': 'DE', 'neighborhoods': ['Gallus']}, {'id': 'w2WhrxBAwfP2zbIvnmw9cw', 'alias': 'long-island-summer-lounge-frankfurt-am-main-4', 'name': 'Long Island Summer Lounge', 'address': 'Parkhaus Börse, Parkdeck 7, 60313 Frankfurt am Main, Germany', 'latitude': 50.115179888015, 'longitude': 8.67548033595085, 'business_page_link': 'https://www.yelp.com/biz/long-island-summer-lounge-frankfurt-am-main-4', 'rating': 2.9, 'review_count': 77, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/plqH3qO9XDNw4V0Wvh37dw/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/w2WhrxBAwfP2zbIvnmw9cw', 'phone': '+4915161509889', 'country': 'DE', 'neighborhoods': ['Innenstadt']}, {'id': 'TrfZbYwG00ylA5OPO6d3dA', 'alias': 'flemings-selection-hotel-frankfurt-city-frankfurt-am-main', 'name': 'Flemings Selection Hotel Frankfurt-City', 'address': 'Eschenheimer Tor 2, 60318 Frankfurt Am Main, Germany', 'latitude': 50.1173529, 'longitude': 8.6801148, 'business_page_link': 'https://www.yelp.com/biz/flemings-selection-hotel-frankfurt-city-frankfurt-am-main', 'rating': 3.8, 'review_count': 18, 'price_range': '€€€', 'photo': 'https://s3-media0.fl.yelpcdn.com/bphoto/VhKQ__h0QOB-lFUT3UoZxw/348s.jpg', 'photos_page_link': 'https://www.yelp.com/biz_photos/TrfZbYwG00ylA5OPO6d3dA', 'phone': '+49694272320', 'country': 'DE', 'neighborhoods': ['Innenstadt']}]}

In [48]:
list2=[]
data2=[]
for i in range(len(response2.json()['data'])):
    list2=[response2.json()['data'][i]['name'],response2.json()['data'][i]['latitude'],response2.json()['data'][i]['longitude'],response2.json()['data'][i]['rating'],response2.json()['data'][i]['review_count'],response2.json()['data'][i]['price_range']]
    data2.append(list2)
df2=pd.DataFrame(data2)
df2.columns=['name','latitude','longtitude','rating','review count','price range']
df2['city']="Frankfurt"
df2

,name,latitude,longtitude,rating,review count,price range,city
0,LugInsLand,50.117526,8.679976,3.4,96,€€€,Frankfurt
1,Gekko House,50.106086,8.652833,2.5,2,,Frankfurt
2,Long Island Summer Lounge,50.115180,8.675480,2.9,77,€€€,Frankfurt
3,Flemings Selection Hotel Frankfurt-City,50.117353,8.680115,3.8,18,€€€,Frankfurt

In [53]:
dataset=pd.concat([df,df1,df2],ignore_index=True)
dataset

,name,latitude,longtitude,rating,review count,price range,city
0,Klunkerkranich,52.482160,13.431854,4.3,122,€€,Berlin
1,Gallery Rooftop Bar,52.504494,13.442135,5.0,2,,Berlin
2,Rooftop Terrace Bar & Lounge,52.515766,13.394096,3.4,5,,Berlin
3,Monkey Bar,52.505377,13.336890,3.3,164,€€€,Berlin
4,Bebel Bar & Lounge,52.515790,13.394244,4.0,17,€€€€,Berlin
5,Soho House,52.527609,13.415473,3.8,88,€€€,Berlin
6,Deck 5,52.549561,13.415130,3.6,109,€€,Berlin
7,Weekend Club,52.523080,13.416489,3.1,114,€€€,Berlin
8,The Circus,52.529403,13.401310,4.5,35,€€,Berlin
9,Amano Rooftop Bar,52.528246,13.402823,3.8,21,€€€,Berlin
10,The Exchange,40.037094,-76.305147,3.6,143,$$,Manheim
11,The Sandwich Factory Sports Lounge,40.095272,-76.305423,3.2,83,$,Manheim
12,Altana Rooftop lounge,40.037682,-76.304317,2.4,88,$$$,Manheim
13,Lancaster Marriott at Penn Square,40.036910,-76.304928,3.2,142,$$,Manheim
14,551 West,40.037151,-76.316605,3.7,103,$$,Manheim
15,Tellus360,40.037694,-76.304430,3.7,167,$$,Manheim
16,Plough,40.036910,-76.304928,3.6,89,,Manheim
17,LugInsLand,50.117526,8.679976,3.4,96,€€€,Frankfurt
18,Gekko House,50.106086,8.652833,2.5,2,,Frankfurt
19,Long Island Summer Lounge,50.115180,8.675480,2.9,77,€€€,Frankfurt
20,Flemings Selection Hotel Frankfurt-City,50.117353,8.680115,3.8,18,€€€,Frankfurt

In [54]:
dataset.to_csv('rooftop_data.csv', index=False)